before_script:
  - python3 -m venv test_env
  - source test_env/bin/activate
  - pip install --no-cache-dir -i https://nexus.meteoswiss.ch/repository/python-all/simple -r requirements.txt

stages:
  - test
  - deploy

variables:
  HTTP_PROXY: http://proxy.meteoswiss.ch:8080
  HTTPS_PROXY: https://proxy.meteoswiss.ch:8080
  TWINE_REPOSITORY_URL: http://nexus.meteoswiss.ch:8081/repository/python-mch/
  TWINE_USERNAME: python-mch
  TWINE_PASSWORD: pwd4python-mch

tests:
  stage: test
  script:
    - pip install --no-cache-dir -i https://nexus.meteoswiss.ch/repository/python-all/simple pytest pytest-cov
    - pytest --cov-report term-missing --cov=opendap_protocol
  tags:
    - app

deploy:
  stage: deploy
  script:
    - pip install --no-cache-dir -i https://nexus.meteoswiss.ch/repository/python-all/simple --upgrade setuptools
    - pip install --no-cache-dir -i https://nexus.meteoswiss.ch/repository/python-all/simple twine wheel
    - python setup.py bdist_wheel
    - twine upload dist/*
  tags:
    - app
  only:
    - tags
